work
Anna-er/todo pull request #1
Opened 2023-10-10 19:54 UTC by Anna-er

Добавлен код

2023-10-10 22:17 UTC, kirill-stupakov requested changes
То, что вне папочки vite-project, лучше удалить, т.к. не используется. Ну и перенести её содержимое в корень репозитория

И надо бы форматнуть всё это (с помощью [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) например)

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/db.json
> +      "id": 5
Порядок полей в таких однотипных конструкциях лучше чтоб был одинаковый

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/public/vite.svg
Это же не иконка vite :)
Такие штуки называют обычно favicon

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +
пустая строчка

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +import * as React from 'react';
это можно сократить до одной строчки
```JS
import { useState, useEffect, FC } from 'react'
```

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +const TODO_LIST_ENDPOINT = 'http://localhost:3000/todos/'
Если вдруг ты захочешь это где-нибудь задеплоить, то тебе сюда придётся написать url стороннего сервиса. При этом хочется, чтобы при разработке всё же запросы шли на локалхост.
Такие проблемы решаются с помошью [переменных окружения](https://www.telerik.com/blogs/beginners-guide-environment-variables#:~:text=Environment%20variables%20allow%20us%20to,functions%20available%20to%20the%20code.), которые устанавливаются разные на деплое и локальной машине.

Надо создать в корне файл `.env` и туда пихать такие строчки, причём обязательно добавив его в гитигнор. И ещё создать файл `.env.example`, который в отличие от предыдущего коммитится и является примером заполненного `.env` файла (чтобы допустим люди не гадали, ожидает ли твоё приложение слэш в конце url-ов)

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +    const [input, setInput] = useState<string>("");
в данном случае явное указание типа не нужно. И название лучше заменить на что-то более понятное (типа `newTodoName` или чего-то такого)

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +            })
есть более удобная обёртка над fetch --- [axios](https://axios-http.com/docs/intro).
Он освобождает как минимум от за`json`ивания и раз`json`ивания данных

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +            })
Как завещал Дмитрий Косарев, по феншуйному функциональному программированию `map` должен принимать чистую функцию, то есть без сайдэффектов вроде запросов на сервер. Лучше наверное в `handleToggle` передавать всю тудушку, а не только id, тогда можно будет сразу запрос отправить, не ища её в массиве.

Плюс тебе json-сервер ответом вернёт изменённыю тудушку, лучше её записывать в состояние. Ведь цель этого стейта --- отображать данные на сервере, а тут ты как бы пытаешься угадать, какие там данные запишутся.

А чтобы не искать нужную тудушку даже при обновлении стейта, можно вместо массива использовать словарь, и по ключу сразу обновлять. Но это если прям душнить, в данном случае наверное и так норм

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +        if (input != "" && input.split(' ').join('') != "") {
Лучше всегда использовать двойное равенство, за исключением исключительных случаев конечно же :)

А ещё это можно сделать через одно условие:
```JS
if (input.trim() !== "")
```

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +        (document.getElementById("inp") as HTMLInputElement).value = "";
Вообще ссылки на DOM-ноды лучше хранить через useRef, но в данном случае и это не нужно, если у инпута установить `value={input}`. Тогда он будет автоматически обновляться с обновлением стейта

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +        fetch(TODO_LIST_ENDPOINT + id.toString(), {
лучше при составлении одной строки из нескольких использовать template literal:
```JS
fetch(`${TODO_LIST_ENDPOINT}/${id}`)
```
Ну и `.toString()` тут не нужен, числа умеют сами в строки конвертироватся :)

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +            if (r.ok) {
а если не ok ?

Надо кстати добавить показ ошибки, если какой-то реквест не удался

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                console.log(newTodos);
лог

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                        <input type="checkbox" style={{ margin: '0.4rem' }} name="todo" id="item" value={todo.id} checked={todo.completed} readOnly />
А зачем тут `value` указывать? Чекбоксы используют свойство `checked`, а `value` у них используется для [другого](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value)

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                        <input type="checkbox" style={{ margin: '0.4rem' }} name="todo" id="item" value={todo.id} checked={todo.completed} readOnly />
Инлайн стили :)

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                        <label id="item">
А зачем тут id?

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                        <label id="item">
Лейблы кстати без свойства `htmlFor` лучше не использовать, так они к инпуту не привязываются

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +            <input className="input-text" type="text" id="inp" placeholder="Add todo item" onChange={(e) => setInput(e.currentTarget.value)} />
`id` не нужен

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                    <div className="items"
множественное число

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                        onClick={() => handleToggle(todo.id)}
Вообще обычно такую логику делают всё-таки при клике на чекбокс

У тебя же допустим может быть в тудушке какая-то ссылка, на которую хочется либо нажать, либо выделить и скопировать. В обоих случаях сработает ещё и onclick

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +}
Въезд запрещён.
![image](https://github.com/Anna-er/todo/assets/58115151/14eb8ed2-80c1-432f-8e33-79afb5f98f74)

Лучше оставлять пустые строчки в конце файлов, чтобы гитхаб (и @vs9h) на это не ругался

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/index.css
> +  overflow-wrap: break-word;
Обычно это не очень хорошая идея так слова переносить. Лучше [вот так](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/)

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/index.css
> +  margin-bottom: 30px;
Удобнее использовать [shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/margin#constituent_properties) для margin-а (и padding-а), его читать легче:
```CSS
margin: 70px 0 30px;
```

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/index.css
> +  color: #00000000;
Это просто прозначные цвета, потому что последняя компонента в 0

Если хочешь что-то отключить, то так и надо писать:
```CSS
border: none;
background: none;
color: transparent;
```

А вообще мне кажется лучше скрывать кнопку совсем через [conditional rendering](https://react.dev/learn/conditional-rendering) или через
```CSS
.items:not(:hover) .remove-button {
  display: none;
}
```

2023-10-10 22:17 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
Вообще файлы компонентов лучше класть в отдельную папочку и у каждого делать свой файл стилей

2023-10-12 13:44 UTC, Anna-er commented on vite-project/src/TodoList.tsx
> +                        <input type="checkbox" style={{ margin: '0.4rem' }} name="todo" id="item" value={todo.id} checked={todo.completed} readOnly />
А как тут без него? Тут же стиль зависит от todo.completed

2023-10-12 13:46 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                        <input type="checkbox" style={{ margin: '0.4rem' }} name="todo" id="item" value={todo.id} checked={todo.completed} readOnly />
Этот коммент относится к
```JSX
style={{ margin: '0.4rem' }}
```

2023-10-12 13:56 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                        <input type="checkbox" style={{ margin: '0.4rem' }} name="todo" id="item" value={todo.id} checked={todo.completed} readOnly />
Кстати даже это
```JSX
 style={{ textDecoration: todo.completed ? "line-through" : "none", color: todo.completed ? "#8E8E8E" : "#000000" }}
```
можно переписать через className:

```JSX
className={`items${todo.completed ? ' completed' : ''}`}
```

А чтобы не было мазохизма с пробелами при при таком присоединении класснеймов (особенно если их будет несколько), можно использовать пакет [classnames](https://www.npmjs.com/package/classnames)

```JSX
className={cn('items', todo.completed && 'completed')}
```

2023-10-12 14:47 UTC, Anna-er commented on vite-project/src/TodoList.tsx
> +                        onClick={() => handleToggle(todo.id)}
Я когда подвязала лейбл к чекбокcу через htmlFor они начали считаться одним целым и при нажатии на текст все равно происходит onClick(

2023-10-12 14:54 UTC, kirill-stupakov commented on vite-project/src/TodoList.tsx
> +                        onClick={() => handleToggle(todo.id)}
Можно вообще тут label не использовать :)

2023-10-27 20:14 UTC, merged